[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5
    Rotate_Wait       30
    Mem_Buf_Limit     64MB
    Skip_Long_Lines   On
    DB                /tmp/fluent-bit-docker.db
    DB.Sync           Normal

[FILTER]
    Name         parser
    Match        docker.*
    Key_Name     log
    Parser       json
    Preserve_Key On
    Reserve_Data On

[FILTER]
    Name    modify
    Match   docker.*
    Remove  stream

[OUTPUT]
    Name                es
    Match               docker.*
    Host                ${ELASTIC_HOST}
    Port                ${ELASTIC_PORT}
    HTTP_User           ${ELASTIC_INGEST_USERNAME}
    HTTP_Passwd         ${ELASTIC_INGEST_PASSWORD}
    Logstash_Format     On
    Logstash_Prefix     fandogh-logs
    Suppress_Type_Name  On
    Replace_Dots        On
    Generate_ID         On
    Retry_Limit         False
